---
title: "Tesi2"
author: "Giovanni Santoru"
date: "2024-01-25"
output: html_document
---


```{r}
#Installing libraries

install.packages("dplyr")
library(dplyr)
install.packages("readr")
library(readr)
```


```{r}
library(readr)
CH_wave1 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave1.csv")
CH_wave1 <- CH_wave1 %>%
  select(-"...1")

CH_wave2 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave2.csv")
CH_wave2 <- CH_wave2 %>%
  select(-"...1")

CH_wave4 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave4.csv")
CH_wave4 <- CH_wave4 %>%
  select(-"...1")

CH_wave5 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave5.csv")
CH_wave5 <- CH_wave5 %>%
  select(-"...1")

CH_wave6 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave6.csv")
CH_wave6 <- CH_wave6 %>%
  select(-"...1")

View(CH_wave1)
```

```{r}
FNRES_wave1 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/FNRES_wave1.csv")
FNRES_wave2 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/FNRES_wave2.csv")
FNRES_wave4 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/FNRES_wave4.csv")
FNRES_wave5 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/FNRES_wave5.csv")
FNRES_wave6 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/FNRES_wave6.csv")

FNRES_wave4 %>% 
  count(mergeid) %>% 
  filter(n > 1)

FNRES_wave1 <- FNRES_wave1 %>% distinct(mergeid, .keep_all = TRUE)
FNRES_wave2 <- FNRES_wave2 %>% distinct(mergeid, .keep_all = TRUE)
FNRES_wave4 <- FNRES_wave4 %>% distinct(mergeid, .keep_all = TRUE)
FNRES_wave5 <- FNRES_wave5 %>% distinct(mergeid, .keep_all = TRUE)
FNRES_wave6 <- FNRES_wave6 %>% distinct(mergeid, .keep_all = TRUE)
  

```

```{r}
educ1 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ1.csv")
educ2 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ2.csv")
educ4 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ4.csv")
educ5 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ5.csv")
educ6 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ6.csv")

colnames(educ1)


```

```{r}
DN_dt1 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt1.csv")
DN_dt2 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt2.csv")
DN_dt4 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt4.csv")
DN_dt5 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt5.csv")
DN_dt6 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt6.csv")

```

```{r}
CV_wave1 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave1.csv")
CV_wave2 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave2.csv")
CV_wave4 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave4.csv")
CV_wave5 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave5.csv")
CV_wave6 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave6.csv")

CV_wave1 %>%
  count(is.na(age_int))
  

nrow(CV_wave6)
```


```{r}
CF_wave1 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave1.csv")
CF_wave2 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave2.csv")
CF_wave4 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave4.csv")
CF_wave5 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave5.csv")
CF_wave6 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave6.csv")

library(readr)
CF_wave1 <- read_csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/DataCamp/Dataset/CF_wave1.csv")
View(CF_wave1)
```

```{r}
install.packages("ivtools")
library(ivtools)
install.packages("stats")

```


```{r}
library(dplyr)
install.packages("purrr")
library(purrr)
library(tidyr)
library(haven)



# Define the column names
year_cols <- paste0("ch006_", 1:20)
gender_cols <- paste0("ch005_", 1:20)

# Define the sorting function
sort_years_and_align_genders <- function(years, genders) {
  combined <- data.frame(year = years, gender = genders, stringsAsFactors = FALSE)
  combined <- combined[order(combined$year, na.last = TRUE), ]
  # If there are fewer years than 20, append NA values to maintain the length
  sorted_years <- combined$year
  sorted_genders <- combined$gender
  list(years = sorted_years, genders = sorted_genders)
}

# Apply the function to each row
share4ch <- sharew4_rel8_0_0_ch %>%
  rowwise() %>%
  mutate(
    sorted_info = list(sort_years_and_align_genders(unlist(across(all_of(year_cols))),
                                                    unlist(across(all_of(gender_cols)))))
  ) %>%
  ungroup()

# Now that we have a list column called sorted_info with sorted years and genders,
# we can separate them into individual columns.
share4ch <- share4ch %>%
  mutate(sorted_info = pmap(list(select(., all_of(year_cols)), select(., all_of(gender_cols))),
                            sort_years_and_align_genders))

# Now, create the year and gender columns separately
for (i in seq_along(year_cols)) {
  share4ch[[year_cols[i]]] <- map_dbl(share4ch$sorted_info, pluck, "years", i)
  share4ch[[gender_cols[i]]] <- map_dbl(share4ch$sorted_info, pluck, "genders", i)
}

# Replace NA values with explicit NAs of the appropriate type
share4ch <- share4ch %>%
  mutate(
    across(all_of(year_cols), ~replace_na(., NA_integer_)),
    across(all_of(gender_cols), ~replace_na(., NA_integer_))
  )

# Print the data frame to verify the results
print(share4ch)

nrow(share4ch)
nrow(sharew4_rel8_0_0_ch)
nrow(CH_wave4)
nrow(CH_wave4c)
```


```{r}
#Controlli

Controshare2 <- sharew2_rel8_0_0_ch %>%
  select(mergeid, ch005_1:ch005_6, ch006_1:ch006_6)

share2chx <- share2ch %>%
  select(mergeid, ch005_1:ch005_6, ch006_1:ch006_6)

filter(Controshare2, mergeid== "AT-017366-03")

```

```{r}
filter(share2chx, mergeid== "AT-017366-03")
```
```{r}
filter(Tot_dataset2, mergeid== "AT-017366-03")
```

