---
title: "Tesi Dataset"
author: "Giovanni Santoru"
date: "2023-12-21"
output: html_document

---
```{r}
#Installing libraries

install.packages("haven")
library(haven)
install.packages("dplyr")
library(dplyr)
```

```{r}
#Importing Datas COGNITIVE FUNCTION 
library(haven)
library(dplyr)

CF_wave1 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_cf.dta")

CF_wave2  <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew2_rel8-0-0_cf.dta")

CF_wave4 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_cf.dta")

CF_wave5 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_cf.dta")

CF_wave6 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_cf.dta")


#CREATING A SINGLE COLUMN FOR THE DELAYED RECALL TEST RESULT


CF_wave4 <- CF_wave4 %>%
  mutate(
    delayed_recall = coalesce(cf113tot, cf114tot, cf115tot, cf116tot)
  )
CF_wave5 <- CF_wave5 %>%
  mutate(
    delayed_recall = coalesce(cf113tot, cf114tot, cf115tot, cf116tot))
  
CF_wave6 <- CF_wave6  %>%
  mutate(
    delayed_recall = coalesce(cf113tot, cf114tot, cf115tot, cf116tot))

#CREATING A SINGLE COLUMN FOR THE IMMEDIATE RECALL TEST RESULT


CF_wave4 <- CF_wave4 %>%
  mutate(
    immediate_recall = coalesce(cf104tot, cf105tot, cf106tot, cf107tot))

CF_wave5 <- CF_wave5 %>%
  mutate(
    immediate_recall = coalesce(cf104tot, cf105tot, cf106tot, cf107tot))

CF_wave6 <- CF_wave6 %>%
  mutate(
    immediate_recall = coalesce(cf104tot, cf105tot, cf106tot, cf107tot))

#Selecting Variables

CF_wave1 <- CF_wave1 %>%
select("mergeid", "verbal_fluency" = "cf010_", "delayed_recall" = "cf016tot", "immediate_recall" = "cf008tot")

CF_wave2 <- CF_wave2 %>%
select("mergeid", "verbal_fluency" = "cf010_", "delayed_recall" = "cf016tot", "immediate_recall" = "cf008tot")

CF_wave4 <- CF_wave4 %>%
select("mergeid", "verbal_fluency" = "cf010_", "delayed_recall",  "immediate_recall")

CF_wave5 <- CF_wave5 %>%
select("mergeid", "verbal_fluency" = "cf010_", "delayed_recall",  "immediate_recall")

CF_wave6 <- CF_wave6 %>%
select("mergeid", "verbal_fluency" = "cf010_", "delayed_recall",  "immediate_recall")


write.csv(CF_wave1,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave1.csv", row.names = FALSE)
write.csv(CF_wave2,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave2.csv", row.names = FALSE)
write.csv(CF_wave4,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave4.csv", row.names = FALSE)
write.csv(CF_wave5,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave5.csv", row.names = FALSE)
write.csv(CF_wave6,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CF_wave6.csv", row.names = FALSE)
```



```{r}
#Importing Data on CV

library(haven)
CV_wave1 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_cv_r.dta")

CV_wave2 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew2_rel8-0-0_ALL_datasets_stata/sharew2_rel8-0-0_cv_r.dta")

CV_wave4 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_cv_r.dta")

CV_wave5 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_cv_r.dta")

CV_wave6 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_cv_r.dta")



CV_wave1 <- CV_wave1 %>% 
  mutate(wave_id = 1)

CV_wave2 <- CV_wave2 %>% 
  mutate(wave_id = 2)

CV_wave4 <- CV_wave4 %>% 
  mutate(wave_id = 4)

CV_wave5 <- CV_wave5 %>% 
  mutate(wave_id = 5)

CV_wave6 <- CV_wave6 %>% 
  mutate(wave_id = 6)

library(dplyr)

CV_wave1 <- CV_wave1 %>%
select("mergeid", "country", "wave_id", "gender", "age_in"="age2004", "age_int", "mobirth", "yrbirth") 
 
CV_wave2 <- CV_wave2 %>%
select("mergeid", "country", "wave_id", "gender", "age_in" ="age2007", "age_int", "mobirth", "yrbirth")  

CV_wave4 <- CV_wave4 %>%
select("mergeid", "country", "wave_id", "gender", "age_in" ="age2011", "age_int", "mobirth", "yrbirth")

CV_wave5 <- CV_wave5 %>%
select("mergeid", "country", "wave_id", "gender", "age_in" ="age2013", "age_int", "mobirth", "yrbirth")

CV_wave6 <- CV_wave6 %>%
select("mergeid", "country", "wave_id", "gender", "age_in" ="age2015", "age_int", "mobirth", "yrbirth")


write.csv(CV_wave1,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave1.csv", row.names = FALSE)
write.csv(CV_wave2,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave2.csv", row.names = FALSE)
write.csv(CV_wave4,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave4.csv", row.names = FALSE)
write.csv(CV_wave5,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave5.csv", row.names = FALSE)
write.csv(CV_wave6,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CV_wave6.csv", row.names = FALSE)
```




```{r}
#Importing Generated Variable Education ISCED
library(haven)
educ1 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_gv_isced.dta")

educ2 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew2_rel8-0-0_ALL_datasets_stata/sharew2_rel8-0-0_gv_isced.dta")

educ4 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_gv_isced.dta")

educ5 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_gv_isced.dta")

educ6 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_gv_isced.dta")




educ1 <- educ1 %>%
  select("mergeid", "isced1997_r") 

educ2 <- educ2 %>%
  select("mergeid", "isced1997_r") 

educ4 <- educ4 %>%
  select("mergeid", "isced1997_r") 

educ5 <- educ5 %>%
  select("mergeid", "isced1997_r") 

educ6 <- educ6 %>%
  select("mergeid", "isced1997_r") 


write.csv(educ1,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ1.csv", row.names = FALSE)
write.csv(educ2,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ2.csv", row.names = FALSE)
write.csv(educ4,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ4.csv", row.names = FALSE)
write.csv(educ5,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ5.csv", row.names = FALSE)
write.csv(educ6,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/educ6.csv", row.names = FALSE)
```

```{r}
DN_wave1 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_dn.dta")

DN_dt2 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew2_rel8-0-0_ALL_datasets_stata/sharew2_rel8-0-0_dn.dta")

DN_dt4 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_dn.dta")

DN_dt5 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_dn.dta")

DN_dt6 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_dn.dta")


DN_dt1 <- DN_wave1 %>%
select("mergeid", "yeduc"="dn010_" , "Born_foreign_c" = "dn004_")

DN_dt2 <- DN_dt2 %>%
  select("mergeid", "yeduc"="dn010_" , "Born_foreign_c" = "dn004_")

DN_dt4 <- DN_dt4 %>%
  select("mergeid", "yeduc"="dn010_" , "Born_foreign_c" = "dn004_")

DN_dt5 <- DN_dt5 %>%
  select("mergeid", "yeduc"="dn010_" , "Born_foreign_c" = "dn004_")

DN_dt6 <- DN_dt6 %>%
  select("mergeid", "yeduc"="dn010_" , "Born_foreign_c" = "dn004_")
```


```{r}
write.csv(DN_dt1,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt1.csv", row.names = FALSE)
write.csv(DN_dt2,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt2.csv", row.names = FALSE)
write.csv(DN_dt4,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt4.csv", row.names = FALSE)
write.csv(DN_dt5,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt5.csv", row.names = FALSE)
write.csv(DN_dt6,"C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/DN_dt6.csv", row.names = FALSE)
```


```{r}
#Impoting Data on Social Network

sharew4_rel8_0_0_gv_networks <- read_dta("C:/Users/gsant/OneDrive/Tesi/Dataset/sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_gv_networks.dta")
View(sharew4_rel8_0_0_gv_networks)

sharew4_rel8_0_0_gv_networks %>%
select(contains("contact"))  
```

```{r}
#Importing CHILDREN DATA

library(haven)
CH_wave1 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_ch.dta")

CH_wave2 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew2_rel8-0-0_ALL_datasets_stata/sharew2_rel8-0-0_ch.dta")

CH_wave4 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_ch.dta")

CH_wave5 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_ch.dta")

CH_wave6 <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_ch.dta")

```


```{r}
#SELECTING THE VARIABLES

CH_wave1 <- CH_wave1 %>%
  mutate(across(starts_with("ch014_"), ~as.numeric(as.character(.)), .names = "numeric_{.col}")) %>%
  mutate(sum_ch014 = rowSums(select(., starts_with("numeric_ch014_")), na.rm = TRUE)) %>%
  mutate(avg_contact = sum_ch014 / 12) %>%
  select("mergeid", "coupleid1", "number_children" = "ch001_", "natural_children"="ch002_", "child1.sex" = "ch005_1", "child2.sex" = "ch005_2", "child1.ybirth" = "ch006_1", "child2.ybirth" = "ch006_2", "sum_ch014", "avg_contact") 

colnames(CH_wave1)

write.csv(CH_wave1, "C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave1.csv")

CH_wave2 <- CH_wave2 %>%
  mutate(across(starts_with("ch014_"), ~as.numeric(as.character(.)), .names = "numeric_{.col}")) %>%
  mutate(sum_ch014 = rowSums(select(., starts_with("numeric_ch014_")), na.rm = TRUE)) %>%
  mutate(avg_contact = sum_ch014 / 12) %>%
  select("mergeid", "coupleid1" = "coupleid2" , "number_children" = "ch001_", "natural_children" = "ch002_", "child1.sex" = "ch005_1", "child2.sex" = "ch005_2", "child1.ybirth" = "ch006_1", "child2.ybirth" = "ch006_2", "sum_ch014", "avg_contact") 

write.csv(CH_wave2, "C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave2.csv")

CH_wave4 <- CH_wave4 %>%
  mutate(across(starts_with("ch014_"), as.numeric)) %>%
  mutate(sum_ch014 = rowSums(select(., starts_with("ch014_")), na.rm = TRUE)) %>%
  mutate(avg_contact = sum_ch014 / 12) %>%
       rowwise() %>%
  mutate(natural_children = case_when(
    all(is.na(c_across(starts_with("ch002_")))) ~ NA_real_,  # Restituisce NA se tutti i valori sono NA
    any(c_across(starts_with("ch002_")) == 5) ~ 0,  # Restituisce 0 se almeno un valore è 5
    all(c_across(starts_with("ch002_")) %in% c(1, NA), na.rm = TRUE) ~ 1,  # Restituisce 1 se tutti i valori sono 1, ignorando NA
    TRUE ~ NA_real_  # Caso di default, dovrebbe essere coperto dai casi sopra
  )) %>%
  ungroup() %>%
  select("mergeid", "coupleid1" = "coupleid4", "number_children" = "ch001_", "natural_children", "child1.sex" = "ch005_1", "child2.sex" = "ch005_2", "child1.ybirth" = "ch006_1", "child2.ybirth" = "ch006_2", "sum_ch014", "avg_contact") 
  
write.csv(CH_wave4, "C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave4.csv")
  


CH_wave5 <- CH_wave5 %>%
  mutate(sum_ch014 = rowSums(select(., starts_with("ch014_")), na.rm = TRUE)) %>%
mutate(avg_contact = sum_ch014 / 12) %>%
rowwise() %>%
   mutate(natural_children = case_when(
    all(is.na(c_across(starts_with("ch002_")))) ~ NA_real_, 
    any(c_across(starts_with("ch002_")) == 5) ~ 0,  
    all(c_across(starts_with("ch002_")) %in% c(1, NA), na.rm = TRUE) ~ 1, TRUE ~ NA_real_
  )) %>%
  ungroup() %>%
  select("mergeid", "coupleid1" = "coupleid5", "number_children" = "ch001_", "natural_children", "child1.sex" = "ch005_1", "child2.sex" = "ch005_2", "child1.ybirth" = "ch006_1", "child2.ybirth" = "ch006_2", "sum_ch014", "avg_contact")  

write.csv(CH_wave5, "C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave5.csv")

CH_wave6 <- CH_wave6 %>%
mutate(sum_ch014 = rowSums(select(., starts_with("ch014_")), na.rm = TRUE)) %>%
mutate(avg_contact = sum_ch014 / 12) %>%
select("mergeid", "coupleid1" = "coupleid6", "number_children" = "ch001_", "natural_children"="ch302_", "child1.sex" = "ch005_1", "child2.sex" = "ch005_2", "child1.ybirth" = "ch006_1", "child2.ybirth" = "ch006_2", "sum_ch014", "avg_contact") 

write.csv(CH_wave6, "C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave6.csv")

```


```{r}
write.csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave1.csv", row.names = FALSE)
write.csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave2.csv", row.names = FALSE)
write.csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave4.csv", row.names = FALSE)
write.csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave5.csv", row.names = FALSE)
write.csv("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/CH_wave6.csv", row.names = FALSE)

```

```{r}
sharew1_rel8_0_0_hh <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_hh.dta")
View(sharew1_rel8_0_0_hh)

```

```{r}
Tot_datasetx <- bind_rows(Tot_wave1x, Tot_wave2x, Tot_wave4x, Tot_wave5x, Tot_wave6x) 
  Tot_datasetx <- Tot_datasetx %>%
    select(mergeid, wave_id, avg_contact, isced1997_r, thinc, hnetw, Born_foreign_c, yeduc)

Tot_datasetx <- Tot_datasetx %>%
group_by(mergeid) %>%
  arrange(mergeid, wave_id) %>% # Ensure the data is ordered before filling
  fill(number_children, .direction = "downup") %>%
  fill(natural_children, .direction = "downup") %>%
  fill(child1.sex, .direction = "downup") %>%
  fill(child2.sex, .direction = "downup") %>%
  fill(child1.ybirth, .direction = "downup") %>%
  fill(child2.ybirth, .direction = "downup") %>%
  ungroup()

Tot_dataset <- Tot_dataset %>%
  mutate(cubage = age_in^3) %>%
  mutate(two_children_same_sex = as.integer(child1.sex == child2.sex)) 


  
nrow(Tot_dataset)


```

```{r}
#If I want lastest variables
%>%
  group_by(mergeid)
  relocate(wave_id, .after = mergeid) %>%
  mutate(wave_id = as.numeric(wave_id)) %>%
  group_by(mergeid) %>%
  slice_max(wave_id, n=1) %>%
  ungroup() 
```


```{r}
Tot_dataset1 <- Tot_dataset %>%
  filter(!is.na(delayed_recall) & !is.na(immediate_recall) & !is.na(verbal_fluency)) %>%
  mutate(age_in = as.numeric(age_in)) %>%
  filter(age_in >= 65, nchild >= 2) %>%
  filter(natural_children == 1)
 
nrow(Tot_dataset1)
```
```{r}
library(haven)
sharew1_rel8_0_0_cv_r <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_cv_r.dta")
View(sharew1_rel8_0_0_cv_r)

sharew4_rel8_0_0_cv_r <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_cv_r.dta")

sharew2_rel8_0_0_cv_r <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew2_rel8-0-0_ALL_datasets_stata/sharew2_rel8-0-0_cv_r.dta")

count(sharew6_rel8_0_0_cv_r, is.na(yrbirth))

library(haven)
sharew4_rel8_0_0_cv_r <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_cv_r.dta")

sharew5_rel8_0_0_cv_r <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_cv_r.dta")

sharew6_rel8_0_0_cv_r <- read_dta("C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_cv_r.dta")
```
```{r}
Easyshare_bornabrd <- easySHARE_rel8_0_0 %>%
  select(mergeid, wave_id = wave, Born_abroad = dn004_mod, gender = female, age) %>%
  filter(wave_id <= 6) %>%
  mutate(gender = if_else(gender == 1, 0, 1))
```


```{r}
Tot_dataset2  <- Tot_dataset2 %>%
  select(-gender.x) %>%
  rename("gender" = "gender.y")

Tot_dataset2 %>%
  distinct(child2.sex)
```

```{r}
write.csv(Tot_dataset2, "C:/Users/gsant/OneDrive - Università degli Studi di Sassari/Desktop/Dataset/Tot_dataset2.csv")
```

